HairSalon/Models/Client.cs
using System.Collections.Generic;
using MySql.Data.MySqlClient;

namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public int StylistId { get; set; }
    public string Name { get; set; }
    public string Note { get; set; }
  }

}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public virtual DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public HairSalonContext(DbContextOptions options) : base(options) { }
  }

}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }

    public int StylistId { get; set; }
    public string StylistName { get; set; }
    public string Specialty { get; set; }
    public int Rate { get; set; }
    public virtual ICollection<Client> Clients { get; set; }
  }

}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using HairSalon.Models;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> clientList = _db.Clients.ToList();
      ViewBag.ClientList = clientList;
      return View();
    }

    public ActionResult Create()
    {
      ViewBag.StylistCount = _db.Stylists.Count();
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "StylistName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Show(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      ViewBag.Client = thisClient;

      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == thisClient.StylistId);
      ViewBag.Stylist = thisStylist;
      return View();
    }
    public ActionResult Edit(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);

      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "StylistName");

      return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Show", new { id = client.ClientId });
    }

    public ActionResult Delete(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      ViewBag.Client = thisClient;
      return View();
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfimed(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }

}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using HairSalon.Models;

namespace HairSalon.Controllers
{
  public class HomeController : Controller
  {
    private readonly HairSalonContext _db;

    public HomeController(HairSalonContext db)
    {
      _db = db;
    }

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

    public ActionResult Search(string search)
    {
      ViewBag.Results = _db.Clients.Where(client => client.Name == search).ToList();
      ViewBag.StylistResults = _db.Stylists.Where(stylist => stylist.StylistName == search || stylist.Specialty == search).ToList();
      return View();
    }

  }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using HairSalon.Models;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> stylistList = _db.Stylists.ToList();
      ViewBag.StylistList = stylistList;
      return View();
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Show(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      ViewBag.Stylist = thisStylist;
      ViewBag.ClientList = _db.Clients.Where(client => client.StylistId == id).ToList();
      return View();
    }
    public ActionResult Edit(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      ViewBag.Stylist = thisStylist;
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      ViewBag.Stylist = thisStylist;
      return View();
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfimed(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }

}

HairSalon/Views/Clients/Create.cshtml
@{
    Layout = "_Layout";
}

@model HairSalon.Models.Client;

<div class="col-md-6 offset-md-3">
    @if( ViewBag.StylistCount == 0 )
    {
      <h2 class="client-header">Please enter a stylist</h2>
      <p class="text-center">You must enter a stylist before you can enter a client.</p>
      <div class="text-center">
        @Html.ActionLink("Add A Stylist", "Create", "Stylists", null, new {@class="btn btn-success"})
      </div>
    }
    else
    {
      @using (Html.BeginForm())
      {
        <div class="form-box">
          <div class="form-header2">Add A Client</div>
          <div class="form-body">
            <div class="form-group">
              @Html.LabelFor(model => model.Name)
              @Html.TextBoxFor(model => model.Name, new { @class="form-control", @placeholder = "Client's Name", required = "required"})
            </div>
            <div class="form-group">
              @Html.LabelFor(model => model.Note)
              @Html.TextBoxFor(model => model.Note, new { @class="form-control", @placeholder = "What are they like?"})
            </div>
            <div class="form-group">
              @Html.LabelFor(model => model.StylistId)
              @Html.DropDownList("StylistId", (IEnumerable<SelectListItem>)ViewBag.PriorityID, new {@class="form-control"})
            </div>
            <button type="submit" class="btn btn-primary btn-block">Add</button>
          </div>
        </div>
      }
    }
</div>

HairSalon/Views/Clients/Delete.cshtml
@{
    Layout = "_Layout";
}

<div class="col-md-6 offset-md-3">
  <h2 class="text-center">Delete Client</h2>
  @using (Html.BeginForm())
  {
    <div class="form-box">
      <div class="form-header">
        Delete Client : @ViewBag.Client.Name
      </div>
      <div class="form-body">
        <p>Are you sure you want Delete</p>
        <button type="submit" class="btn btn-danger btn-block">Delete</button>
      </div>
    </div>
  }
</div>

HairSalon/Views/Clients/Edit.cshtml
@{
    Layout = "_Layout";
}
@model HairSalon.Models.Client;

<div class="col-md-6 offset-md-3">
  <div class="form-box">
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.ClientId)
      <div class="form-header">Edit details for @Model.Name </div>
      <div class="form-body">
        <div class="form-group">
          @Html.LabelFor(model => model.Name)
          @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class="form-control" } })
         
        </div>
        <div class="form-group">
          @Html.LabelFor(model => model.Note)
          @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class="form-control" }})
        </div>
        <div class="form-group">
          <label for="StylistId">Stylist</label>
          @Html.DropDownList("StylistId", (IEnumerable<SelectListItem>)ViewBag.PriorityID, new {@class="form-control"})
        </div>
        <button type="submit" class="btn btn-primary btn-block">Edit </button>
      </div>
    }
  </div>
</div>

HairSalon/Views/Clients/Index.cshtml
@{
    Layout = "_Layout";
}
@using HairSalon.Models;

<div class="row">
    <div class="col-md-6 offset-md-3">
    <h2 class="client-header">Client Index</h2>
        @if ( ViewBag.ClientList.Count == 0)
        {
            <h3 class="text-center">Please Enter A Client</h3>
            <div class="text-center">
                <a href="/clients/create">
                    <button class="btn btn-primary">Add A Client</button>
                </a>
            </div>
        } 
        else
        {
            <div class="list-group" id="list-tab" role="tablist">
            @foreach (Client client in ViewBag.ClientList)
            {   
                <div class="list-group-item list-group-item-action">
                    <img src="~/img/icons8-male-user-90.png" alt="profile place holder" class="profile-img">

                    @Html.ActionLink($"{client.Name}", "Show", new {id = client.ClientId})
                </div>
            }
            </div>

            @Html.ActionLink("Add A Client", "Create", null, htmlAttributes: new {@class="btn btn-primary btn-lg btn-block"})
        }
    </div>
</div>

HairSalon/Views/Clients/Show.cshtml
@{
    Layout = "_Layout";
}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="client-box--show">
      <div class="client-box--header">
        Client : @ViewBag.Client.Name
      </div>
      <div class="client-box--center">
       <p>Stylist : @ViewBag.Stylist.StylistName</p>
       <p>Notes : @ViewBag.Client.Note</p>

      </div>


      <div class="client-box--footer">
        @Html.ActionLink("Edit Details", "Edit", new {id = ViewBag.Client.ClientId}, new {@class="btn btn-info"})
        @Html.ActionLink("Delete Client", "Delete", new { id = ViewBag.Client.ClientId}, new {@class="btn btn-danger"})
      </div>
    </div>
  </div>
</div>

HairSalon/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}

<main role="main">
  <div class="jumbotron">
    <div class="col-sm-8 mx-auto">
      <h1>Hair Salon Tracker</h1>
      <p>
        Hair Salon Tracker is a tool to keep track of your stylists and clients. Using this tool, you can update your hair-recording sheet, track stylists' visits, and submit stylist and client information to a central database for the full supervision of all your stylists. Make sure your stylist appointments and records are correct and properly filled out.
      </p>
      <p>
        Laser Eye Surgery
      </p>
      <p>
        Tallahassee Clinic of Tampa provides eye surgery in Tallahassee, Florida. Our top-notch vision professionals make the most of the time you spend here.
      </p>
      <p>
        Your next visit to the clinic may include an eye exam, which allows the clinician to diagnose any underlying issues or disease. After a comprehensive examination, eye surgery is performed.
      </p>

      <p>
        If you have Haircut, you will have your own categories as well.
      </p>

      <ol>
        <li> 
          Trading Cards ( Trading cards allow you to use real world currency to trade with your clients.   Your stylists keep a little bit of each card in their bank and you get to decide how many of these you use per week. Make up, fragrance, and clothes by hair stylist may all be given for a fixed rate of $2 or $3, depending on the card.  
        </li>
        <li>
          Hand stamped shaving  ( WTF is this? I mean it is probably a decoy based on it having my personality on it)
        </li>
      </ol>
      <p><strong> This text was generated by Talk to Transformer. A free an open text generating AI. </strong></p>
      <p>
        <a class="btn btn-primary" href="https://talktotransformer.com/" role="button" target="_blank">Check out Talk to Transformer</a>
      </p>
    </div>
  </div>
</main>

HairSalon/Views/Home/Search.cshtml
@{
    Layout = "_Layout";
}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h2 class="stylist-header">Search Results</h2>
    @if (ViewBag.Results.Count == 0 && ViewBag.StylistResults.Count == 0)
    {
      <h2 class="text-center"> Found Not Matches </h2>
    }
    else
    {
      <div class="list-group" id="list-tab" role="tablist">
        @foreach (var client in ViewBag.Results)
        {
            <h3 class="text-center">Client Results</h3>
            @Html.ActionLink($"{client.Name}", "Show", "Clients", new {id = client.ClientId}, new {@class="list-group-item list-group-item-action"})
        }
        @foreach (var stylist in ViewBag.StylistResults)
        {
            <h3 class="text-center">Stylists Results</h3>
            @Html.ActionLink($"{stylist.StylistName}", "Show", "Stylists", new {id = stylist.StylistId}, new {@class="list-group-item list-group-item-action"})
        }
      </div>
    }

  </div>
</div>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/styles.css">
    
    <title>Hair Salon Tracker</title>
  </head>
  <body>
    <div class="container">
      @await Html.PartialAsync("_Navbar")
      @RenderBody()
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
  </body>
</html>

HairSalon/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
  <a class="navbar-brand" href="#">Salon Tracker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample09">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link home" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link stylists" href="/stylists">Stylists</a>
      </li>
      <li class="nav-item">
        <a class="nav-link client" href="/clients">Clients</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown09" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Quick Menu</a>
        <div class="dropdown-menu" aria-labelledby="dropdown09">
          <a class="dropdown-item" href="/stylists/create">Add A Stylist</a>
          <a class="dropdown-item" href="/clients/create">Add A Client</a>
        </div>
      </li>
    </ul>
    <div class="form-inline my-2 my-md-0">
      @using (Html.BeginForm("search", "Home"))
      {
        <input class="form-control" type="text" placeholder="Search" name="search" aria-label="Search">

      }
    </div>
  </div>
</nav>

HairSalon/Views/Stylists/Create.cshtml
@{
    Layout = "_Layout";
}

@model HairSalon.Models.Stylist;

<div class="col-md-6 offset-md-3">
  <div class="form-box">
    @using (Html.BeginForm())
    {
      <div class="form-header">Add A Stylist</div>
      <div class="form-body">
        <div class="form-group">
          @Html.LabelFor(model => model.StylistName)
          @Html.TextBoxFor(model => model.StylistName, new { @class="form-control", @placeholder = "Stylist's Name", required = "required"})
        </div>
        <div class="form-group">
          @Html.LabelFor(model => model.Specialty)
          @Html.TextBoxFor(model => model.Specialty, new { @class="form-control", @placeholder = "Specialty"})
        </div>
        <div class="form-group">
          @Html.LabelFor(model => model.Rate)
          @* @Html.TextBoxFor(model => model.Rate, new { @class="form-control", @placeholder = "Hourly Rate"}) *@
          @Html.TextBoxFor(model => model.Rate, new { @class="form-control", @placeholder = "Hourly Rate", @type = "number"})
        </div>
        <button type="submit" class="btn btn-primary btn-block">Add</button>
      </div>
    }
  </div>
</div>

HairSalon/Views/Stylists/Delete.cshtml
@{
    Layout = "_Layout";
}

<div class="col-md-6 offset-md-3">
  <h2 class="text-center">Stylist Delete</h2>
  @using (Html.BeginForm())
  {
    <div class="form-box">
      <div class="form-header">
        Delete Stylist : @ViewBag.Stylist.StylistName
      </div>
      <div class="form-body">
        <p>Are you sure you want Delete</p>
        <button type="submit" class="btn btn-danger btn-block">Delete</button>
      </div>
    </div>
  }
</div>

HairSalon/Views/Stylists/Edit.cshtml
@{
    Layout = "_Layout";
}
@model HairSalon.Models.Stylist;

<div class="col-md-6 offset-md-3">
  <div class="form-box">
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.StylistId)
      <div class="form-header">Edit details for @ViewBag.Stylist.StylistName </div>
      <div class="form-body">
        <div class="form-group">
          @Html.LabelFor(model => model.StylistName)
          @Html.EditorFor(model => model.StylistName, new { htmlAttributes = new { @class="form-control" } })
         
        </div>
        <div class="form-group">
          @Html.LabelFor(model => model.Specialty)
          @Html.EditorFor(model => model.Specialty, new { htmlAttributes = new { @class="form-control" }})
        </div>
        <div class="form-group">
          @Html.LabelFor(model => model.Rate)
          @Html.EditorFor(model => model.Rate,new { htmlAttributes = new { @class="form-control", @type = "number" }})
        </div>
        <button type="submit" class="btn btn-primary btn-block">Edit </button>
      </div>
    }
  </div>
</div>

HairSalon/Views/Stylists/Index.cshtml
@{
    Layout = "_Layout";
}
@using HairSalon.Models;

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h2 class="text-center stylist-header">Stylist Index</h2>  
    @if ( ViewBag.StylistList.Count == 0)
    {
      <h3 class="text-center">Please Enter A Stylist</h3>
      <div class="text-center">
        <a href="/stylists/create">
          <button class="btn btn-primary">Add A Stylist</button>
        </a>
      </div>
    } 
    else
    {
      <div class="list-group" id="list-tab" role="tablist">
      @foreach (Stylist stylist in ViewBag.StylistList)
      {   
        <div class="list-group-item list-group-item-action">
          <img src="~/img/icons8-barber-scissors-100.png" alt="stylist profile image placeholder" class="stylist-img">
          @Html.ActionLink($"{stylist.StylistName}", "Show", new {id = stylist.StylistId})
        </div>
          
          
      }
      </div>

      @Html.ActionLink("Add A Stylist", "Create", null, htmlAttributes: new {@class="btn btn-primary btn-block btn-lg"})
    }
  </div>
</div>

HairSalon/Views/Stylists/Show.cshtml
@{
    Layout = "_Layout";
}
@using HairSalon.Models;
@model HairSalon.Models.Stylist;

<div class="row">
  <div class="col-md-6 offset-md-3">

    <div class="show-box">
      <div class="show-header">
        Stylist : @ViewBag.Stylist.StylistName
      </div>
      <div class="show-body">
        <p>Specialty : @ViewBag.Stylist.Specialty</p>
        <p>Rate : $@ViewBag.Stylist.Rate Per Hour</p>
      </div>
      <div class="show-footer">
        @Html.ActionLink("Edit Details", "Edit", new {id = ViewBag.Stylist.StylistId}, new {@class="btn btn-info"})
        @Html.ActionLink("Delete Stylist", "Delete", new { id = ViewBag.Stylist.StylistId}, new {@class="btn btn-danger"})
      </div>
    </div>

  </div>
</div>

  <h3 class="text-center">Client Count : @ViewBag.ClientList.Count</h3>
<div class="row">
  <div class="col-md-8 offset-md-2 client-listout">
      @foreach (Client client in @ViewBag.ClientList)
      {
        <div class="client-box--body">
          <div class="client-box--header">
            @client.Name
          </div>
          <div class="client-box--center">
            <a href="/clients/show/@client.ClientId"><button class="btn btn-info">Details</button></a>
          </div>
        </div>
      }

  </div>
</div>